### ISSUE TITLE
Chybejici zaznam VT v HDO HOURLY TODAY

### ISSUE THREAD

**Issue by S474N** [Antrac1t/HomeAssistant-EGDdistribuce#14]
Mam nasledujici nastaveni:
```
binary_sensor:
  - platform: egddistribuce
    name: egdTAR
    psc: "smart"         # "smart" pro chytre elektromery, jinak PSC
    code_a: "Cd56"   # kod smart elektromeru
    price_vt: "1.53385"
    price_nt: "1.37943"
```
Tarif D56d, NT 22 hodin, VT 2 hodiny (a to 0:00-1:00 a 12:00-13:00). Bohuzel v prehledu dnesniho dne chybi ona druha hodina VT:

![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/16512337/680aab72-83de-4053-acc1-f4568dadff2d)
