### ISSUE TITLE
Prázdné atributy HDO entity

### ISSUE THREAD

**Issue by budisek** [Antrac1t/HomeAssistant-EGDdistribuce#34]
Zdravím, 

používal jsem integraci bez problému, ale už nějakou dobu mi nic neukazuje.

V atributech nic není.

<img width="790" alt="image" src="https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/35574450/1e83b8c2-eb86-4fd7-9559-078cbe3d4b81">

Nastavení v YAML je toto (ty ceny nesedí, jen testuji.):

```
binary_sensor:
  - platform: egddistribuce
    name: hdo
    psc: "smart"
    code_a: "Cd45"
    price_vt: "7.79"
    price_nt: "5.45"
```

Co může být špatně?
