### ISSUE TITLE
Smart elektroměr

### ISSUE THREAD

**Issue by jansams** [Antrac1t/HomeAssistant-EGDdistribuce#8]
Dobrý den, ahoj,
měl jsem klasické HDO - vše bez problémů fungovalo.
Teď mě vyměnili elektroměr za nějaký smart a ten má integrované HDO. 
Příkaz HDO je teď Acd56. Půjde to nějak nastavit ?

**Comment by Antrac1t** [comment]
Ahoj, je potřeba přepsat addon i pro smart elektroměry, bohužel časove s k žádné úpravě nedostanu.

**Comment by S474N** [comment]
Stejny problem, mam kod `CD56`. 

Tedy zadna uprava tohoto pluginu nebude? Neexistuje nejaky jiny plugin, co funguje?

**Comment by LubosKovar** [comment]
pls jak máte přesně zápis v Configuration.yaml? Me to proste pořád hází chybu....
Invalid config for [binary_sensor.egddistribuce]: [ode_a] is an invalid option for [binary_sensor.egddistribuce]. Check: binary_sensor.egddistribuce->ode_a. (See ?, line ?).

**Comment by Antrac1t** [comment]
Chyba pri implementaci a nebo pri nainstalovani? Plugin na mem HA jede bez problemu

**Comment by Antrac1t** [comment]
> pls jak máte přesně zápis v Configuration.yaml? Me to proste pořád hází chybu.... Invalid config for [binary_sensor.egddistribuce]: [ode_a] is an invalid option for [binary_sensor.egddistribuce]. Check: binary_sensor.egddistribuce->ode_a. (See ?, line ?).
napiste prosim Vas config

**Comment by Antrac1t** [comment]
> Stejny problem, mam kod `CD56`.
> 
> Tedy zadna uprava tohoto pluginu nebude? Neexistuje nejaky jiny plugin, co funguje?


Upravu pluginu pro nove elektromery neplanuji.

**Comment by S474N** [comment]
Skoda, dival jsem se, ze to stahuje soubor `hdoZaznam.json` z https://hdo.distribuce24.cz/casy a ty smartmetery tam jsou uvedeny (vubec se tam neresi PSC, je to pro celou lokalitu):

![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/16512337/535bd998-2ca1-45d2-8211-3cbc02da2c9e)

Umet python, tak bych to udelal, ale bohuzel mimo me schopnosti.

BWT jinak Lubos uz je vyresen.

**Comment by Antrac1t** [comment]
> Skoda, dival jsem se, ze to stahuje soubor `hdoZaznam.json` z https://hdo.distribuce24.cz/casy a ty smartmetery tam jsou uvedeny (vubec se tam neresi PSC, je to pro celou lokalitu):
> 
> ![image](https://user-images.githubusercontent.com/16512337/258631373-535bd998-2ca1-45d2-8211-3cbc02da2c9e.png)
> 
> Umet python, tak bych to udelal, ale bohuzel mimo me schopnosti.
> 
> BWT jinak Lubos uz je vyresen.

nasel jsem chvilku casu zkuste stahnout a prepsat v HA binary_sensor.py a downloader.py + upravit config na 
    psc: SM
    code_a: "AD57"
    code_b: "0"
    code_dp: "0"

a dejte vedet jestli to neco najde

**Comment by S474N** [comment]
Hlasi mi to `HDO vypnuto`.

Jen teda ja nemam tarif D57, ale D56, respektive kod je `Cd56`.

**Comment by jirkacisar** [comment]
> Zatim to zkousim a nevypada to, ze by to vracelo spravne data, protoze mezi 12-13 ma byt NT.

A sensor.time máte definovaný?

**Comment by S474N** [comment]
Tak uprimne receno, vubec nevim, co se po me chce :D HA mam teprve druhy den a spis se s tim seznamuji a v navodu o zprovozneni zadny `sensor.time` nevidim.

**Comment by jirkacisar** [comment]
> EDIT: jo tak, ja reagoval na samotny projekt, ne ten skript. ;)

Aha, tak to jsme se nepochopili, nevadi :-)

**Comment by S474N** [comment]
Tak bohuzel zadna zmena.

Zapis v config.yaml:
```
binary_sensor:
  - platform: egddistribuce
    name: HDO
    psc: SM
    code_a: "Cd56"
    code_b: "0"
    code_dp: "0"
```

Jeden den zkouseno i:
```
binary_sensor:
  - platform: egddistribuce
    name: HDO
    psc: "SM"
    code_a: "Cd56"
    code_b: "0"
    code_dp: "0"
```


![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/16512337/7ef09841-b406-4165-a289-8c245c1f7e94)

**Comment by LubosKovar** [comment]
Potvrzuji jen chování, co popisují kolegové. Staré HDO se načítá ok, nové s výše uvedenými zápisy nikoliv.

**Comment by WikiHA** [comment]
Smart elektroměry mají v datovém souboru u platnosti "od" a "do" uveden rok "9999" a časy jsou tedy asi platné stále. Vyřešil jsem to nahrazením řádek 47-49 tímto kódem.

`    for itemData in output_hdo_dict:
        current_year = datetime.datetime.now().year
        if int(itemData['od']['rok']) == 9999:
            if int(itemData['od']['mesic']) < int(itemData['do']['mesic']):
                year = current_year
            else:
                year = current_year + 1
        else:
            year = itemData['od']['rok']
        str_date_time_od = f"{current_year}-{itemData['od']['mesic']}-{itemData['od']['den']}"
        str_date_time_do = f"{year}-{itemData['do']['mesic']}-{itemData['do']['den']}"
`

**Comment by S474N** [comment]
Tak jsem si v logu vsiml tohoto:
![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/16512337/68f75e8d-f5b5-4263-afec-ca6aff46c9e5)

**Comment by Antrac1t** [comment]
jedine upravit odkazy z https na http, zalezi jakou mate verzi HA, a co tam menili, ja popravde pres 1.5 roku neprovadel aktualizaci ...

**Comment by S474N** [comment]
Jedu komplet na vsem nejnovejsim, zkusim to upravit.

**Comment by pmisak** [comment]
Díky za tu úpravu. Funguje mi následující yaml:
```
binary_sensor:
  - platform: egddistribuce
    name: HDO_nizky_tarif
    psc: SM
    code_a: "ACD25"
    code_b: "0"
    code_dp: "0"
```

**Comment by Antrac1t** [comment]
> Díky za tu úpravu. Funguje mi následující yaml:
> 
> ```
> binary_sensor:
>   - platform: egddistribuce
>     name: HDO_nizky_tarif
>     psc: SM
>     code_a: "ACD25"
>     code_b: "0"
>     code_dp: "0"
> ```

takze kod pro smart meter jiz mam brat jako funkcni a uzavrit tiket? Otazka co [S474N]

**Comment by WikiHA** [comment]
Jak jsem psal výše: Kód regionu u smart elektroměru nemusí být jen na 2 znaky, ale třeba je tam i kód "TOU". Navíc člověk bez znalosti json nemá žádnou šanci jej někde najít. Na stránkách eg.d se to nikde nezobrazuje. V případě smart metru bych (po zběžné analýze dat) úplně filtraci na kód regionu vypustil a hledal data jen podle code_a. Takto jsem si to v kódu upravil a funguje mi to.

**Comment by Antrac1t** [comment]
> Jak jsem psal výše: Kód regionu u smart elektroměru nemusí být jen na 2 znaky, ale třeba je tam i kód "TOU". Navíc člověk bez znalosti json nemá žádnou šanci jej někde najít. Na stránkách eg.d se to nikde nezobrazuje. V případě smart metru bych (po zběžné analýze dat) úplně filtraci na kód regionu vypustil a hledal data jen podle code_a. Takto jsem si to v kódu upravil a funguje mi to.

ano, bohuzel nemam cas vyhrazeny na ladeni addonu, prvotne byl udelan jen pro me ucely a pouze jsem ho gitnul a kdo chce muze ho nainstalovat, popr forknout a upravit ...

**Comment by S474N** [comment]
Bohuzel moje Cd56 ma VT az po pulnoci, takze drive to overit nemohu :D

**Comment by WikiHA** [comment]
@Antrac1t : Chápu, nikdo času nemá nazbyt. S gitem si zatím moc nerozumím, tak jsem si skripty upravil přímo na HA. Přikládám je níže, třeba to někomu pomůže. S mým kódem elektroměru to funguje. V configu je pak definován takto:
```
binary_sensor:
  - platform: egddistribuce
    name: HDO_nizky_tarif
    psc: "smart"         # "smart" pro chytre elektromery, jinak PSC
    code_a: "Cd2526_2"   # kod smart elektromeru
```
[egd.zip](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/files/12381154/egd.zip)

**Comment by S474N** [comment]
@WikiHA po tve uprave jiz vse jede!

![image](https://github.com/Antrac1t/HomeAssistant-EGDdistribuce/assets/16512337/45e6b582-0285-48c8-86e4-e5cf014964f1)

**Comment by cewbdex** [comment]
Dnes u nás nainstalovali smart meter, nemohl jsem na něm najít jiný kód než `d57`. EGD ho v JSONu má, ale je u něj region `TOU` a předpokládám, že z toho důvodu ani výše zmíněný archiv nefunguje, je to tak? Jak vidím, archiv zde byl nahrán, ale není implementován v repozitáři, hodilo by se někomu, abych otevřel PR a kód byl v HACS?

```
        "region": "TOU",
        "skupinaPovelu": "MO-EV",
        "kodHdo_A": "d57",
        "kodHdo_B": "A0B0DP0",
        "kodHdo_C": "0B0DP0",
        "kodHdo_D": "0B0P0",
        "kodHdo_E": "A0B0P0",
        "A": "0",
        "B": "0",
        "DP": "00",
```

**Comment by S474N** [comment]
Vsak to je ten stejny pripad jako u me, ne?

```
binary_sensor:
  - platform: egddistribuce
    name: HDO_nizky_tarif
    psc: "smart"         # "smart" pro chytre elektromery, jinak PSC
    code_a: "Cd57"   # kod smart elektromeru
    code_b: "0"   # kod smart elektromeru
    code_dp: "0"   # kod smart elektromeru
```
